language: python
python:
  - "2.7.18"
  - "3.5.9"
  - "3.6.12"
  - "3.7.9"
  - "3.8.6"
dist: xenial     # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
install:
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
script:
  - py.test --cov=slimta
  - flake8 slimta
  - pytype -k
after_success:
  - coveralls
